name: Node.js CI + Docker

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:   # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Setup Node.js 18
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - run: npm ci

      # 4. Build production assets
      - run: npm run production

      # 5. Setup Docker Buildx (for multi-platform builds)
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 6. Login to GitHub Container Registry (GHCR)
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # 7. Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/karan7687/symbi-eat:latest
            ghcr.io/karan7687/symbi-eat:${{ github.sha }}
