name: Node.js CI + Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: npm run production

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login using GitHub token (no secrets needed)
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
git add .github/workflows/ci.yml
git commit -m "Add Node.js + Docker public CI workflow"
git push origin main
