name: Node.js CI Demo

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:   # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - run: npm ci

      # 4. Build production assets
      - run: npm run production

      # 5. Fake Docker step (just echo)
      - name: Fake Docker build
        run: echo "Docker build step skipped (no secrets needed)"
